### PR TITLE
target='_blank' link

### LINKED ISSUE #82: Pop-up windows are prevented
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description

Firefox prevents pop-up windows when opening links which has `target="_blank"` on following links. It should open links in new tabs when that link selected.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Press `f`
2. Select links with `target="_blank"`

#### System configuration

- Operating system: Linux
- Firefox version: v57 developer edition
- Vim-Vixen version: 0.2

#### Console logs

Any relevant log in developer tools:

### PR DESCRIPTION
**Pull request by ueokande**
close #82 

This change allow to open a link with `target='_blank'`.  This avoid preventing a new tab by the browser.

### CODE REVIEW

File: src/content/components/common/follow.js [hunk 1]
```diff
@@ -68,7 +69,7 @@ export default class Follow {
     return browser.runtime.sendMessage({
       type: messages.OPEN_URL,
       url: element.href,
-      newTab: this.newTab,
+      newTab: true,
```
Comment (usk) [inline src/content/components/common/follow.js]: This change allows to open a new tab even when newTab is false.
I think it's better to prioritize user's newTab option.
